### PR TITLE
implement builtin string_of_int

### PR DESCRIPTION
**Pull request by yunlanli**
@LeoQiao18 @jc4883 @yiming-fang Why are we using `int8_t` for all primitive values? Why didn't we use `char` for `_pml_char` for instance?

### CODE REVIEW

**Comment by leoqiao18** [comment]
> @LeoQiao18 @jc4883 @yiming-fang Why are we using `int8_t` for all primitive values? Why didn't we use `char` for `_pml_char` for instance?

Are you referring to using `int8_t *` as `_pml_val`? Remember how we wanted to use `void *`, but LLVM actually complained about that. Apparently LLVM does not like `void *` as a type; you need to use an actually data type for pointers. This is why we changed to `int8_t *`. The particular choice of `int8_t` was arbitrary.

**Comment by yunlanli** [comment]
> > @LeoQiao18 @jc4883 @yiming-fang Why are we using `int8_t` for all primitive values? Why didn't we use `char` for `_pml_char` for instance?
> 
> Are you referring to using `int8_t *` as `_pml_val`? Remember how we wanted to use `void *`, but LLVM actually complained about that. Apparently LLVM does not like `void *` as a type; you need to use an actually data type for pointers. This is why we changed to `int8_t *`. The particular choice of `int8_t` was arbitrary.

The reason for using `int8_t *` as `_pml_val` makes a lot of sense. My confusion, however, is on the choice of primitive types shown below:

```c
/* pocaml primitives */
typedef		int8_t		_pml_char;
typedef		int8_t		_pml_bool;
typedef		int8_t		_pml_unit;
typedef		int32_t		_pml_int;
```

Although we are returning to LLVM an `int8_t *` for each value (ptr to primitives), the exact type of these primitives could be of any type of our choice (since we know the exact accepted types for each builtin function, we can cast them to the appropriate type in our builtins anyways). Why did we choose to represent `_pml_char`, `_pml_bool` and `_pml_unit` all as `int8_t`? When implementing the builtin `string_of_int`, I'm getting this warning from `gcc` because on ARM processors, they seem to expect an `unsigned char *` to the standard C library `sprintf`. I looked up online and discovered whether `char` is represented as signed or unisigned int seems to be processor dependent.

```bash
➜ ./pocamlc -cdf test_lambda_1.pml
gcc -I. -D BUILTIN_DEBUG   -c -o string_of_int.o string_of_int.c
string_of_int.c:19:10: warning: passing '_pml_string' (aka 'signed char *') to parameter of type 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        sprintf(res, "%d", *int_val);
```

Anyways, just want to make sure that we use the types most suitable for our purposes here :)

**Comment by leoqiao18** [comment]
In LLVM, there is no distinction between signed and unsigned integer types (take a look at the StackOverflow answer [here](https://stackoverflow.com/questions/14723532/llvms-integer-types)). As to what we should fix in order to not get this warning, I think we can actually change our typedefs in `builtins.h` to use the more comprehensive C types (for example, use `char` for `_pml_char`). As long as we know that the number of bits corresponds with the number of bits in the LLVM integer types, we should be okay.

**Comment by leoqiao18** [comment]
> In LLVM, there is no distinction between signed and unsigned integer types (take a look at the StackOverflow answer [here](https://stackoverflow.com/questions/14723532/llvms-integer-types)). As to what we should fix in order to not get this warning, I think we can actually change our typedefs in `builtins.h` to use the more comprehensive C types (for example, use `char` for `_pml_char`). As long as we know that the number of bits corresponds with the number of bits in the LLVM integer types, we should be okay.

So, feel free to change the types in `builtins.h` if you'd like.

**Comment by yunlanli** [comment]
> > In LLVM, there is no distinction between signed and unsigned integer types (take a look at the StackOverflow answer [here](https://stackoverflow.com/questions/14723532/llvms-integer-types)). As to what we should fix in order to not get this warning, I think we can actually change our typedefs in `builtins.h` to use the more comprehensive C types (for example, use `char` for `_pml_char`). As long as we know that the number of bits corresponds with the number of bits in the LLVM integer types, we should be okay.
> 
> So, feel free to change the types in `builtins.h` if you'd like.

Cool, gonna change `_pml_char` to use type `char` per the recommendation from [GNU C][1]:

> - signed char: The 8-bit signed char data type can hold integer values in the range of -128 to 127.
> - unsigned char: The 8-bit unsigned char data type can hold integer values in the range of 0 to 255.
> - char: Depending on your system, the char data type is defined as having the same range as either the > signed char or the unsigned char data type (they are three distinct types, however). By convention, you > should use the char data type specifically for storing ASCII characters (such as `m`), including escape > sequences (such as `\n`). 


[1]: https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Data-Types  "GNU C LRM"

**Pull request merged**
